# JAI Bot Bio Class Updater 
# Author: Permanent on JAI 
# Last Update: April / 12 / 2026

[mappings]
_groupCount_6pr3j_208 = _groupCount_6hekb_208
css-27z6xa = 
css-ksvjqq = 
css-19u3gmz = css-19u3gmz
_myChatsButton_zy1kf_133 = _myChatsButton_59rbb_150
_characterInfoMarkdownContent_9gldz_223 = _characterInfoMarkdownContent_123vi_223
_input_1uufu_102 = _input_1a0xb_102
_moderationBlock_gd4gb_320 = _moderationBlock_1s17f_320
_characterInfoShinyBoxInner_9gldz_107 = 
_autoResizeTextarea_48ugw_1 = _autoResizeTextarea_mrqt8_1
_betaBadge_1vfgx_65 = _betaBadge_ud2h5_65
_characterInfoShinyBox_1tqgq_86 = 
