# JAI Bot Bio Class Updater 
# Author: Permanent on JAI 
# Last Update: April / 12 / 2026

[mappings]
_groupCount_6pr3j_208 = _groupCount_6hekb_208
css-27z6xa = css-1jdnh42
css-1bntj9o = css-1bntj9o
css-ksvjqq = css-z5908y
css-19u3gmz = css-19u3gmz
_myChatsButton_zy1kf_133 = _myChatsButton_59rbb_150
_input_1uufu_102 = _input_1a0xb_102
_moderationBlock_gd4gb_320 = _moderationBlock_1s17f_320
_autoResizeTextarea_48ugw_1 = _autoResizeTextarea_mrqt8_1
_betaBadge_1vfgx_65 = _betaBadge_ud2h5_65
null_popoverHeader_fdp8b_126 = _popoverHeader_wpa9q_131
_characterInfoMarkdownContent_9gldz_223 = _characterInfoMarkdownContent_123vi_223
_characterInfoShinyBox_1tqgq_86 = _characterInfoShinyBox_1yi4w_265
_characterInfoShinyBoxInner_9gldz_107 = _characterInfoShinyBoxInner_1yi4w_286
_characterInfoHeader_9gldz_38 = _characterInfoHeader_1yi4w_217
_footer_6pr3j_366 = _footer_1ur42_57
_iosModalWarning_gd4gb_544 = _iosModalWarning_1s17f_544
_iosStatusValue_aekh2_239 = _iosStatusValue_1s17f_239
_bar_1lgb1_26 = _bar_2aaam_26
_scheduleInfoNote_gd4gb_1106 = _scheduleInfoNote_1s17f_1106
_publishModeOption_gd4gb_1039 =  _publishModeOption_1s17f_1039
_quickScheduleButton_gd4gb_940 = _quickScheduleButton_1s17f_940
_scheduledInput_gd4gb_887 = _scheduledInput_1s17f_887
_scheduledReleaseSection_gd4gb_863 = _scheduledReleaseSection_1s17f_863
_iosSettingsSection_gd4gb_35 = _iosSettingsSection_1s17f_35
_iosSelect_gd4gb_805 = _iosSelect_1s17f_805
_iosStatusSection_gd4gb_208 = _iosStatusSection_1s17f_208
_scheduledReleaseInfo_gd4gb_1136 = _scheduledReleaseInfo_1s17f_1136
_scheduledPreview_gd4gb_972 = _scheduledPreview_1s17f_972
_scheduledReleaseWarning_gd4gb_876 = _scheduledReleaseWarning_1s17f_876
_moderationIcon_gd4gb_369n = _moderationIcon_1s17f_369
_hintBox_kzyo9_46 = _hintBox_2ljd6_74
_modal_1uufu_17 = _modal_1a0xb_17
_card_13ngt_2 = _card_128g5_2
_submitButton_1uufu_163 = _submitButton_1a0xb_163
_characterInfoShinyBoxInner_9gldz_107 = _characterInfoShinyBoxInner_1yi4w_286
_moderationReason_gd4gb_405 = _moderationReason_1s17f_405
_groupCount_6pr3j_20 = _groupCount_6hekb_208
_character_13ngt_38 = _character_128g5_38
_autoResizeTextarea_48ugw_1 = _autoResizeTextarea_mrqt8_1
_count_fdehf_7 = _count_138g0_7
css-ne3tzp = css-1d22cyw
_input_1a0xb_102 = _input_1jhaa_228
