# JAI Bot Bio Class Updater 
# Author: Permanent on JAI 
# Last Update: July  / 21 / 2026

[mappings]
_appModalBadge_xxqvx_134 = _appModalBadge_xxqvx_134
_appModalContent_xxqvx_85 = _appModalContent_xxqvx_85
_appModalCta_xxqvx_195 = _appModalCta_xxqvx_195
_archiveButton_di476_217 = _archiveButton_di476_217
_autoResizeTextarea_48ugw_1 = _autoResizeTextarea_mrqt8_1
_banner_2x3bf_17 = _banner_2x3bf_17
_bar_1lgb1_26 = _bar_17iy7_26
_bar_2aaam_26 = _bar_17iy7_26
_baseOverlay_d0q9a_20 = _baseOverlay_d0q9a_20
_betaBadge_1vfgx_65 = _betaBadge_ud2h5_65
_betaBadge_ud2h5_65 = _betaBadge_ud2h5_65
_btn_6hekb_374 = _btn_1fl1d_2
_btnPrimary_6hekb_407 = _btnPrimary_1fl1d_80
_btnSecondary_6hekb_385 = _btnSecondary_6hekb_385
Btn2-purple = Btn2-purple
_button_biys2_21 = _button_biys2_21
_cancelButton_wdl7l_ = _cancelButton_jv6cc_165
_cancelScheduleButton_1s17f_1202 = _cancelScheduleButton_1s17f_1202
_card_128g5_2 = _card_13n8k_2
_card_13n8k_2 = _card_13n8k_2
_cardTitle_13n8k_402 = _cardTitle_13n8k_402
_character_13ngt_38 = _character_128g5_38
_characterInfoHeader_9gldz_38 = _characterInfoHeader_1yi4w_217
_characterInfoMarkdownContent_123vi_223 = _characterInfoMarkdownContent_123vi_223
_characterInfoMarkdownContent_1yi4w_5 = _characterInfoMarkdownContent_1yi4w_5
_characterInfoMarkdownContent_9gldz_223 = _characterInfoMarkdownContent_123vi_223
_characterInfoShinyBox_1tqgq_86 = _characterInfoShinyBox_1yi4w_265
_characterInfoShinyBox_1yi4w_265 = _characterInfoShinyBox_1yi4w_265
_characterInfoShinyBoxInner_123vi_107 = _characterInfoShinyBoxInner_1yi4w_286
_characterInfoShinyBoxInner_1yi4w_286 = _characterInfoShinyBoxInner_1yi4w_286
_characterInfoShinyBoxInner_9gldz_107 = _characterInfoShinyBoxInner_1yi4w_286
_checkboxCard_exkyv_105 = _checkboxCard_exkyv_105
_checkboxCardError_exkyv_112 = _checkboxCardError_exkyv_112
_container_ud2h5_3 = _container_ud2h5_3
_content_1az8j_11 = _content_1yrg6_11
_content_xxqvx_12 = _content_xxqvx_12
_continueButton_amac6_237 = _continueButton_amac6_237
_count_138g0_7 = _count_138g0_7
_count_fdehf_7 = _count_138g0_7
_createButton_1jb5k_14 = glow-on-hover
css-19u3gmz = css-19u3gmz
css-197qci7 = css-197qci7
css-1bntj9o = css-1bntj9o
css-1jdnh42 = css-1jdnh42
css-1vh5zal = css-1vh5zal
css-27z6xa = css-1jdnh42
css-7kiadw = css-7kiadw
css-ksvjqq = css-z5908y
css-ne3tzp = css-1d22cyw
css-z5908y = css-z5908y
_detailModal_6hekb_544 = _detailModal_6hekb_544
_dropzone_pcnch_36 = _dropzone_u16ct_36
_editScheduleButton_1s17f_1180 = _editScheduleButton_1s17f_1180
_expanded_2x3bf_208 = _expanded_2x3bf_208
_expandedInner_2x3bf_220 = _expandedInner_2x3bf_220
_filterButtonOpen_1vsdv_27 = _filterButtonOpen_1vsdv_27
_footer_6pr3j_366 = _footer_1ur42_57
_footer_93ppg_1 = _footer_93ppg_1
_groupCount_6hekb_208 = _groupCount_6hekb_208
_groupCount_6pr3j_20 = _groupCount_6hekb_208
_groupCount_6pr3j_208 = _groupCount_6hekb_208
_groupItem_6hekb_160 = _groupItem_6hekb_160
_hintBox_2ljd6_74 = _hintBox_2ljd6_74
_hintBox_kzyo9_46 = _hintBox_2ljd6_74
_historyItem_10txd_1 = _historyItem_10txd_1
_historyItemFocused_10txd_34 = _historyItemFocused_10txd_34
_holidays2025Pattern1_d0q9a_115 = _holidays2025Pattern1_d0q9a_115
_holidays2025Pattern2_d0q9a_124 = _holidays2025Pattern2_d0q9a_124
_iconError_wpa9q_294 = _iconError_wpa9q_294
_iconInfo_wpa9q_279 = _iconInfo_wpa9q_279
_iconSuccess_wpa9q_284 = _iconSuccess_wpa9q_284
_iconWarning_wpa9q_289 = _iconWarning_wpa9q_289
image-input-dropzone = image-input-dropzone
_inner_2x3bf_31 = _inner_2x3bf_31
_input_1a0xb_102 = _input_jv6cc_126
_input_1gzug_8 = _input_owmrz_7
_input_1uufu_102 = _input_jv6cc_126
_input_exkyv_52 = _input_exkyv_52
_input_wdl7l_100 = _input_jv6cc_126
_inputContainer_1cle1_26 = _inputContainer_o5odd_26
_iosAlert_1s17f_263 = _iosAlert_1s17f_263
_iosModalWarning_1s17f_544 = _iosModalWarning_1s17f_544
_iosModalWarning_gd4gb_544 = _iosModalWarning_1s17f_544
_iosModalWarningText_1s17f_562 = _iosModalWarningText_1s17f_562
_iosSelect_1s17f_805 = _iosSelect_1s17f_805
_iosSelect_gd4gb_805 = _iosSelect_1s17f_805
_iosSettingItem_1s17f_46 = _iosSettingItem_1s17f_46
_iosSettingsSection_1s17f_35 = _iosSettingsSection_1s17f_35
_iosSettingsSection_gd4gb_35 = _iosSettingsSection_1s17f_35
_iosStatusSection_1s17f_208 = _iosStatusSection_1s17f_208
_iosStatusSection_gd4gb_208 = _iosStatusSection_1s17f_208
_iosStatusValue_aekh2_239 = _iosStatusValue_1s17f_239
_loadMoreButton_wpa9q_458 = _loadMoreButton_wpa9q_458
_message_hb27e_61 = _message_hb27e_61
_messageNavigation_1yi4w_348 = _messageNavigation_1yi4w_348
_modal_1uufu_17 = _modal_1a0xb_17
_modal_6hekb_19 = _modal_4i2wy_8
_modal_pru5r_15 = _modal_pru5r_15
_modal_ud2h5_292 = _modal_ud2h5_292
_modalContent_1jhaa_166 = _modalContent_1tnmx_48
_modalContent_wpa9q_692 = _modalContent_wpa9q_692
_modalStatItem_ud2h5_364 = _modalStatItem_ud2h5_364
_modalWarning_wpa9q_763 = _modalWarning_wpa9q_763
_moderationBlock_1s17f_320 = _moderationBlock_1s17f_320
_moderationBlock_gd4gb_320 = _moderationBlock_1s17f_320
_moderationHeader_1s17f_360 = _moderationHeader_1s17f_360
_moderationIcon_gd4gb_369n = _moderationIcon_1s17f_369
_moderationNotes_di476_369 = _moderationNotes_di476_369
_moderationNotification_di476_333 = _moderationNotification_di476_333
_moderationReason_1s17f_405 = _moderationReason_1s17f_405
_moderationReason_gd4gb_405 = _moderationReason_1s17f_405
_moderationSubject_di476_360 = _moderationSubject_di476_360
_motionHeader_1s17f_1361 = _motionHeader_1s17f_1361
_motionModal_1s17f_1339 = _motionModal_1s17f_1339
_motionWarning_1s17f_1459 = _motionWarning_1s17f_1459
_myChatsButton_zy1kf_133 = _myChatsButton_59rbb_150
_navButton_1yi4w_359 = _navButton_1yi4w_359
_notificationsButton_wpa9q_7 = _notificationsButton_wpa9q_7
null_popoverHeader_fdp8b_126 = _popoverHeader_wpa9q_131
_option_pru5r_82 = _option_pru5r_82
_otherInput_pru5r_156 = _otherInput_pru5r_156
_panel_mxoyb_172 = _panel_mxoyb_172
pp-top-bar-logo profile-top-bar-logo glow-logo css-1bmggo3 = pp-top-bar-logo profile-top-bar-logo glow-logo css-1bmggo3
_primaryButton_2ljd6_91 = _primaryButton_2ljd6_91
_priorityHigh_wpa9q_356 = _priorityHigh_wpa9q_356
_priorityLow_wpa9q_364 = _priorityLow_wpa9q_364
_priorityMedium_wpa9q_360 = _priorityMedium_wpa9q_360
_privacyNote_2x3bf_301 = _privacyNote_2x3bf_301
_publishModeOption_gd4gb_1039 = _publishModeOption_1s17f_1039
_quickScheduleButton_gd4gb_940 = _quickScheduleButton_1s17f_940
retry-button = retry-button
_scheduleInfoNote_1s17f_1106 = _scheduleInfoNote_1s17f_1106
_scheduleInfoNote_gd4gb_1106 = _scheduleInfoNote_1s17f_1106
_scheduleTypeOption_1s17f_1231 = _scheduleTypeOption_1s17f_1231
_scheduledInput_1s17f_887 = _scheduledInput_1s17f_887
_scheduledInput_gd4gb_887 = _scheduledInput_1s17f_887
_scheduledPreview_1s17f_972 = _scheduledPreview_1s17f_972
_scheduledPreview_gd4gb_972 = _scheduledPreview_1s17f_972
_scheduledReleaseInfo_1s17f_1136 = _scheduledReleaseInfo_1s17f_1136
_scheduledReleaseInfo_gd4gb_1136 = _scheduledReleaseInfo_1s17f_1136
_scheduledReleaseSection_1s17f_863 = _scheduledReleaseSection_1s17f_863
_scheduledReleaseSection_gd4gb_863 = _scheduledReleaseSection_1s17f_863
_scheduledReleaseWarning_1s17f_876 = _scheduledReleaseWarning_1s17f_876
_scheduledReleaseWarning_gd4gb_876 = _scheduledReleaseWarning_1s17f_876
_searchInput_6hekb_117 = _searchInput_1cdh3_97
_showLess_1bk4j_26 = _showLess_1bk4j_26
_signupTextarea_45b6m_172 = _signupTextarea_45b6m_172
_statItem_ud2h5_121 = _statItem_ud2h5_121
_submitBtn_1gzug_172 = _submitBtn_1gzug_172
_submitButton_1uufu_163 = _submitButton_1a0xb_163
_timeSelect_ud2h5_84 = _timeSelect_ud2h5_84
_title_hb27e_32 = _title_hb27e_32
_tosBox_1gzug_119 = _tosBox_1gzug_119
_tosBoxError_1gzug_127 = _tosBoxError_1gzug_127
_trigger_6hekb_453 = _trigger_4i2wy_213
upload-text = upload-text
